spring.application.name=bff-web
server.port=8081

# ==========================================
# CONEXION A LA MISMA BASE DE DATOS DEL PROYECTO BATCH
# ==========================================
spring.datasource.url=jdbc:mariadb://localhost:3306/bank_batch
spring.datasource.username=root
spring.datasource.password=2785030
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# No modificar el schema, ya existe (lo crea el proyecto batch)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ==========================================
# API KEY para este canal (Web)
# ==========================================
bff.api-key=web-secret-123
